name: Publish update

on:
  push:
    branches: [ "master", "dev" ] 
  schedule:
     - cron: "04 00 * * 0"


env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Create google-services.json
        run: cat /home/runner/work/sangel/sangel/app/google-services.json | base64

      - name: Putting data into google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/sangel/sangel/app/google-services.json

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_FILE }}
        run: |
          TMP_KEYSTORE_FILE_PATH=/home/runner/work/sangel/sangel/app/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/mezhendosina_key.jks
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleRelease --stacktrace

      - name: Get built APK
        uses: actions/upload-artifact@v3
        with:
          name: SGO app.apk
          path: /home/runner/work/sangel/sangel/app/build/outputs/apk/release/app-release.apk

  send-to-channel:
    runs-on: ubuntu-latest
    steps:
      - name: Get APK
        uses: actions/download-artifact@v3
        with:
          name: SGO app.apk
          path: ./

      - name: rename APK
        run: mv /home/runner/work/sangel/sangel/app-release.apk /home/runner/work/sangel/sangel/app-release.apk

      - name: Send file to Telegram channel
        run: curl -F document=@"/home/runner/work/sangel/sangel/app-release.apk" https://api.telegram.org/bot${{ secrets.TELEGRAM_API_TOKEN }}/sendDocument?chat_id=-1002003867686

